### ISSUE TITLE
Add useful readme

### ISSUE THREAD

**Issue by burhanahmeed** [burhanahmeed/covidmonitor#6]
Please DO NOT add spam or useless readme.

**Comment by simeon4real** [comment]
Hello, I'd like to take this up

**Comment by burhanahmeed** [comment]
Do you have any reference for good readme structure ? 

https://github.com/mazipan/quran-offline/blob/master/README.md I think this is a good example of readme for an app/webapp

let me know if you have other references

**Comment by burhanahmeed** [comment]
thank you mas @tiyan-attirmidzi

**Comment by tiyan-attirmidzi** [comment]
> thank you mas @tiyan-attirmidzi

sama2 mas hehe @burhanahmeed
